### PR TITLE
Update index.tsx

### PR DESCRIPTION
**Pull request by frook1**

### CODE REVIEW

**Comment by baughmann** [comment]
@frook1 Merged. Thanks for your contribution:)

**Comment by baughmann** [comment]
@frook1 Note, I will have to wait until after the workday today to publish the changes to NPM. If you need them sooner, let me know.

**Comment by frook1** [comment]
I can wait :)

**Comment by baughmann** [comment]
@frook1 I know I’m delayed. It’s not just this repo, I’m behind on another one too lol. I have tasked myself to do this tonight, sorry for the delay. Hopefully it’s not causing you too much inconvenience

**Comment by baughmann** [comment]
@frook1 `0.1.3` has been published to NPM :)

**Pull request merged**
